apiVersion: v1
kind: Template
metadata:
  name: minio-client

objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: minio-client
  spec:
    selector:
      name: minio-client
    strategy:
      activeDeadlineSeconds: 21600
      type: Rolling
    replicas: 1
    securityContext: {}
    template:
      metadata:
        labels:
          name: minio-client
      spec:
        containers:
        - image: quay.io/duke253/minio-client-centos7:1.7
          imagePullPolicy: Always
          name: minio-client
          ports:
          - containerPort: 9000
            protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 256Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30