apiVersion: v1
kind: Template
metadata:
  name: minio-client

objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: minio-client
  spec:
    selector:
      name: minio-client
    strategy:
      activeDeadlineSeconds: 21600
      type: Rolling
    replicas: 1
    securityContext: {}
    template:
      metadata:
        labels:
          name: minio-client
      spec:
        containers:
        - image: quay.io/duke253/minio-client-centos7:1.5
          imagePullPolicy: Always
          name: minio-client
          ports:
          - containerPort: 9000
            protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 256Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
- kind: Service
  apiVersion: v1
  metadata:
    name: minio-client
  spec:
    ports:
    - name: 9000-tcp
      port: 9000
      protocol: TCP
      targetPort: 9000
    selector:
      deploymentconfig: minio-client
- kind: Route
  apiVersion: v1
  metadata:
    name: minio-client
  spec:
    host:
    to:
      kind: Service
      name: minio-client
    port:
      targetPort: 9000-tcp
parameters:
- description: MINIO_URL
  displayName: MINIO_URL
  name: MINIO_URL
  required: true
  value: %REPLACE_ME%
- description: MINIO_BUCKET
  displayName: MINIO_BUCKET
  name: MINIO_BUCKET
  required: true
  value: %REPLACE_ME%
- description: MINIO_KEY
  displayName: MINIO_KEY
  name: MINIO_KEY
  required: true
  value: %REPLACE_ME%
- description: MINIO_SECRET
  displayName: MINIO_SECRET
  name: MINIO_SECRET
  required: true
  value: %REPLACE_ME%